# Generated by Django 2.2.7 on 2019-11-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondinfo',
            name='Deposit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bondinfo',
            name='House_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bondinfo',
            name='Interest_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bondinfo',
            name='Loan_term',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
