# Generated by Django 2.2.7 on 2019-11-20 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_bondinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondinfo',
            name='User',
        ),
    ]
