# Generated by Django 2.2.7 on 2019-11-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_remove_bondinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondinfo',
            name='Title',
        ),
    ]
